"""USB Pico pointer probe schedule: the Bluetooth hover-rate probe, played from the Pico.

One source for the firmware header and the measurement. It mirrors
hardware/hid_pointer/hover_rate_probe.py so results compare with HID-POINTER-20261004
section 8:
  home, park on clear floor;
  'rates': 4-count reports every 3, 1 and 15 ms, there and back (60, 60, 30 reports);
  'stall': 10 passes of 30 reports one per 15 ms;
  'usb1ms': 10 passes of 60 reports one per 1 ms (frame regularity at USB rate);
  re-home, re-park, then press tests at the park point: a tap, a 10-report upward drag
  at 15 ms, a hover back down, the same drag at 1 ms. Each lift is its own report 1 ms
  after the last move. Hover passes never press.

Usage: PYTHONPATH=<repo>/src schedule.py <out_dir>   writes schedule.h and schedule.json
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

from trueskate_ai.control.hid_pointer import HOME_REPORTS, PARK_POINT, PARK_REPORTS, PARK_STEP, displacement

STEP_US = 15_000
GAP_US = 600_000
PASS_DX = 4
# 60 reports (114 pt) per fast pass leave ~2.6x headroom for rate-dependent acceleration before
# the right edge (park x 109 of 414 pt). The Bluetooth probe sent 100 at 3 ms; compare ratios.
RATES = [(4, 3000, 60), (-4, 3000, 60), (4, 1000, 60), (-4, 1000, 60), (4, 15000, 30), (-4, 15000, 30)]
STALL = [(4, 15000, 30), (-4, 15000, 30)] * 5
USB1MS = [(4, 1000, 60), (-4, 1000, 60)] * 5
DRAG = (0, -8, 10)                 # counts per report, reports
TAP_HOLD_US = 50_000
LIFT_DELAY_US = 1_000
PRESS_GAP_US = 1_000_000
LEAD_MS = 8_000
# Clear play area at the park column (pt); left HUD icons sit at x < 35, the top HUD above y 130.
SAFE_X, SAFE_Y = (60.0, 330.0), (200.0, 600.0)


def build():
    """Events (t_us, dx, dy, buttons), passes and presses with their schedule times."""
    ev, passes, presses = [], [], []
    t = 0

    def add(dx, dy, buttons, step):
        nonlocal t
        ev.append((t, dx, dy, buttons))
        t += step

    def home_and_park(label):
        nonlocal t
        start = t
        for _ in range(HOME_REPORTS):
            add(-127, -127, 0, STEP_US)
        t += 300_000
        for _ in range(PARK_REPORTS):
            add(*PARK_STEP, 0, STEP_US)
        t += GAP_US
        return dict(kind=label, start_us=start, end_us=t)

    sections = [home_and_park('park')]
    for mode, plan in (('rates', RATES), ('stall', STALL), ('usb1ms', USB1MS)):
        for dx, step, n in plan:
            start = t
            for _ in range(n):
                add(dx, 0, 0, step)
            passes.append(dict(mode=mode, dx=dx, step_us=step, reports=n, start_us=start, end_us=t))
            t += GAP_US
    sections.append(home_and_park('repark'))

    # Tap: press, hold, lift (still reports, so the cursor stays at the park point).
    start = t
    add(0, 0, 1, TAP_HOLD_US)
    add(0, 0, 0, PRESS_GAP_US)
    presses.append(dict(kind='tap', start_us=start, lift_us=start + TAP_HOLD_US))
    dx, dy, n = DRAG
    for step, kind in ((STEP_US, 'drag15ms'), (1000, 'drag1ms')):
        start = t
        add(0, 0, 1, step)                       # press in place
        for i in range(n):
            add(dx, dy, 1, step if i < n - 1 else LIFT_DELAY_US)
        lift = t
        add(0, 0, 0, PRESS_GAP_US)               # lift as its own report
        presses.append(dict(kind=kind, step_us=step, reports=n, dx=dx, dy=dy, start_us=start, lift_us=lift))
        if kind == 'drag15ms':                   # hover back to the park point
            for _ in range(n):
                add(-dx, -dy, 0, STEP_US)
            t += GAP_US
    add(0, 0, 0, 0)                              # neutral
    return ev, passes, presses, sections


def modelled_path(events):
    """Modelled cursor positions after re-park, used to keep presses inside the clear area."""
    x, y = PARK_POINT
    out = []
    for t, dx, dy, b in events:
        px, py = displacement(dx, dy)
        x, y = x + px, y + py
        out.append((t, x, y, b))
    return out


def schedule_hash(events) -> str:
    return hashlib.sha256(json.dumps(events).encode()).hexdigest()[:16]


def header(events, digest: str) -> str:
    rows = ',\n'.join(f'  {{{t}u, {dx}, {dy}, {b}}}' for t, dx, dy, b in events)
    return f'''#pragma once
// Generated by schedule.py; do not edit. Schedule hash {digest}.
#include <stdint.h>
struct Event {{ uint32_t t_us; int8_t dx; int8_t dy; uint8_t buttons; }};
static constexpr uint32_t kScheduleHash = 0x{digest[:8]}u;
static constexpr uint32_t kLeadMs = {LEAD_MS}u;
static constexpr uint16_t kEventCount = {len(events)};
static const Event kEvents[kEventCount] = {{
{rows}
}};
'''


def main(out_dir: str):
    events, passes, presses, sections = build()
    digest = schedule_hash(events)
    out = Path(out_dir)
    (out / 'schedule.h').write_text(header(events, digest))
    (out / 'schedule.json').write_text(json.dumps(dict(
        schedule_hash=digest, lead_ms=LEAD_MS, n_events=len(events), duration_us=events[-1][0],
        pass_dx=PASS_DX, passes=passes, presses=presses, sections=sections), indent=1) + '\n')
    print(f'{len(events)} events over {events[-1][0] / 1e6:.2f} s, hash {digest}')


if __name__ == '__main__':
    main(sys.argv[1])
